### ISSUE TITLE
OOM killer triggered

### ISSUE THREAD

**Issue by eduardzamfir** [princeton-computational-imaging/SoaP#5]
Hey,

thanks for this awesome project!

I'm running your demo code, but the training process fails immediately due to the OOM killer. My system has an RTX 4090 with 24GB VRAM and 32GB of RAM. When I set the `--no_raw` flag, I can run the code using only RGB inputs.

Could you provide the minimum compute requirements needed to train with raw inputs? Alternatively, do you have any recommendations to help circumvent this issue?

Thanks!
Eduard

**Comment by Ilya-Muromets** [comment]
This might unfortunately depend on where the OOM is happening. If you are getting to the training stage then changing the `point_batch_size` arg should do the trick, as you can basically just multiple the number of batches in each epoch by 2 and half the number of rays sampled per batch to achieve relatively identical training (with less rays = less compute).

```
    parser.add_argument('--point_batch_size', type=int, default=1024, help="Number of points to sample per dataloader index.")
```

If it's crashing during initialization (e.g., because the RAW data is just really big), then this might be a little more tricky. I think 64gb of RAM should be more than enough to run it, but let me know if this is the case and I can see if there's any code optimization stuff I missed in the main repo.
